paths:
  train_test_split: "training/data/train_test_split.pkl"
  model_output: "models/model.pkl"

vectorizer:
  max_features: 10000
  stop_words: "english"
  ngram_range: (1, 2)

model_type: "rfr" # "gbr" or "rfr"

model:
  n_estimators: 500
  max_depth: 7
  random_state: 42
  learning_rate: 0.05

training:
  cv_folds: 5